// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwEwc8Ue9bKqeQvJuOil51YGvSCznNKEw',
    appId: '1:679654468306:web:a0f06c20617b2431bedb0b',
    messagingSenderId: '679654468306',
    projectId: 'mostro-test',
    authDomain: 'mostro-test.firebaseapp.com',
    storageBucket: 'mostro-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwF5XEuNOC-TQqhLrFJQhNVzbFYSc1sI',
    appId: '1:679654468306:android:eed448d8b546663cbedb0b',
    messagingSenderId: '679654468306',
    projectId: 'mostro-test',
    storageBucket: 'mostro-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8p_RvNfHNKwc-InupojUkOco3t36A4Pw',
    appId: '1:679654468306:ios:0b960156ed20d3a4bedb0b',
    messagingSenderId: '679654468306',
    projectId: 'mostro-test',
    storageBucket: 'mostro-test.firebasestorage.app',
    iosBundleId: 'network.mostro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8p_RvNfHNKwc-InupojUkOco3t36A4Pw',
    appId: '1:679654468306:ios:0b960156ed20d3a4bedb0b',
    messagingSenderId: '679654468306',
    projectId: 'mostro-test',
    storageBucket: 'mostro-test.firebasestorage.app',
    iosBundleId: 'network.mostro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwEwc8Ue9bKqeQvJuOil51YGvSCznNKEw',
    appId: '1:679654468306:web:a85640bd3da48baebedb0b',
    messagingSenderId: '679654468306',
    projectId: 'mostro-test',
    authDomain: 'mostro-test.firebaseapp.com',
    storageBucket: 'mostro-test.firebasestorage.app',
  );
}
