// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKUG4IkZ51YfTjZSCqNdZmT5dVH_ebnA',
    appId: '1:375342057498:web:64f481ab355feea386e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    authDomain: 'mostro-mobile.firebaseapp.com',
    storageBucket: 'mostro-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOrsfYrkIItBLAFbnYmh4HnsxBTnT3y14',
    appId: '1:375342057498:android:4ef7011ab12de38e86e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIc0i_xrVcNz_HILS2jFXUEcgbLKrfKo',
    appId: '1:375342057498:ios:1cfcc24cfe51fbd386e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
    iosBundleId: 'network.mostro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIc0i_xrVcNz_HILS2jFXUEcgbLKrfKo',
    appId: '1:375342057498:ios:1cfcc24cfe51fbd386e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
    iosBundleId: 'network.mostro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcKUG4IkZ51YfTjZSCqNdZmT5dVH_ebnA',
    appId: '1:375342057498:web:2cd68bf87a368a4886e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    authDomain: 'mostro-mobile.firebaseapp.com',
    storageBucket: 'mostro-mobile.firebasestorage.app',
  );
}
