name: Build Flutter macOS Desktop

on:
  workflow_dispatch:  # manual trigger
  push:
    branches: [ main ]

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      # 1. Check-out source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.2'   # match version from main.yml

      # 3. Configure Flutter (disable analytics)
      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter config --enable-macos-desktop

      # 4. Install project dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Generate localization and other required files
      - name: Generate required files
        run: dart run build_runner build -d

      # 6. Extract version from pubspec.yaml
      - name: Extract version
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Version: $version"

      # 7. Analyze code (optional but recommended)
      - name: Analyze code
        run: flutter analyze
        continue-on-error: true   # don't fail build on warnings

      # 8. Build macOS release
      - name: Build macOS release
        run: flutter build macos --release

      # 9. Create zip package for distribution
      - name: Package macOS build
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../mostro_mobile-${{ steps.extract_version.outputs.version }}-macos.zip mostro_mobile.app
          cd ../../../../../
          echo "Created: mostro_mobile-${{ steps.extract_version.outputs.version }}-macos.zip"

      # 10. Upload as artifact (backup)
      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: mostro_mobile-${{ steps.extract_version.outputs.version }}-macos.zip

      # 11. Create GitHub Release and upload
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "mostro_mobile-${{ steps.extract_version.outputs.version }}-macos.zip"
          tag: v${{ steps.extract_version.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          replacesArtifacts: true
