name: "CI Check"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate localization and other required files
        run: dart run build_runner build -d

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
